### PR TITLE
Fix wait for ssh node ready

### LINKED ISSUE #645: TestBench is flaky
https://console.cloud.google.com/cloud-build/builds/6d2150e6-cfb1-4bcb-ae08-8c0403b90d8d?project=ci-account&authuser=1

```
DEBU   Looking up Teleport Enterprise distribution v10.0.0 test:TestIntegrationAuth/TestBootstrap integration/download.go:65
DEBU   Teleport binaries are found in /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin. No need to download anything test:TestIntegrationAuth/TestBootstrap integration/download.go:173
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/teleport version test:TestIntegrationAuth/TestBootstrap integration/integration.go:508
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/tctl version test:TestIntegrationAuth/TestBootstrap integration/integration.go:508
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/tsh version test:TestIntegrationAuth/TestBootstrap integration/integration.go:508
DEBU   License is given as a string, writing it to a file test:TestIntegrationAuth/TestBootstrap integration/integration.go:146
DEBU   Running Auth service: /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/teleport start --debug --config /tmp/teleport-plugins-integration-422323839/teleport-auth-2176199168.yaml test:TestIntegrationAuth/TestBootstrap integration/authservice.go:90
DEBU   Auth service process has been started pid:27953 test:TestIntegrationAuth/TestBootstrap integration/authservice.go:113
DEBU   Found addr of Auth service process: 127.0.0.1:44579 pid:27953 test:TestIntegrationAuth/TestBootstrap integration/authservice.go:151
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/tctl --config /tmp/teleport-plugins-integration-422323839/teleport-auth-2176199168.yaml --auth-server 127.0.0.1:44579 status test:TestIntegrationAuth/TestBootstrap tctl/tctl.go:140
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/tctl --config /tmp/teleport-plugins-integration-422323839/teleport-auth-2176199168.yaml --auth-server 127.0.0.1:44579 create test:TestIntegrationAuth/TestBootstrap tctl/tctl.go:73
DEBU   Terminating Auth service process pid:27953 test:TestIntegrationAuth/TestBootstrap integration/authservice.go:119
DEBU   Looking up Teleport Enterprise distribution v10.0.0 test:TestIntegrationAuth/TestPing integration/download.go:65
DEBU   Teleport binaries are found in /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin. No need to download anything test:TestIntegrationAuth/TestPing integration/download.go:173
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/teleport version test:TestIntegrationAuth/TestPing integration/integration.go:508
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/tctl version test:TestIntegrationAuth/TestPing integration/integration.go:508
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/tsh version test:TestIntegrationAuth/TestPing integration/integration.go:508
DEBU   License is given as a string, writing it to a file test:TestIntegrationAuth/TestPing integration/integration.go:146
DEBU   Running Auth service: /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/teleport start --debug --config /tmp/teleport-plugins-integration-3483365670/teleport-auth-1407457721.yaml test:TestIntegrationAuth/TestPing integration/authservice.go:90
DEBU   Auth service process has been started pid:28386 test:TestIntegrationAuth/TestPing integration/authservice.go:113
DEBU   Found addr of Auth service process: 127.0.0.1:36701 pid:28386 test:TestIntegrationAuth/TestPing integration/authservice.go:151
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/tctl --config /tmp/teleport-plugins-integration-3483365670/teleport-auth-1407457721.yaml --auth-server 127.0.0.1:36701 status test:TestIntegrationAuth/TestPing tctl/tctl.go:140
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/tctl --config /tmp/teleport-plugins-integration-3483365670/teleport-auth-1407457721.yaml --auth-server 127.0.0.1:36701 create test:TestIntegrationAuth/TestPing tctl/tctl.go:73
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/tctl --config /tmp/teleport-plugins-integration-3483365670/teleport-auth-1407457721.yaml --auth-server 127.0.0.1:36701 auth sign --user vladimir --format file --overwrite --out /tmp/teleport-plugins-integration-3483365670/credentials-vladimir-669837799 test:TestIntegrationAuth/TestPing tctl/tctl.go:59
DEBU   Attempting GET 127.0.0.1:36701/webapi/find webclient/webclient.go:119
DEBU   Attempting GET 127.0.0.1:36701/webapi/find webclient/webclient.go:119
WARN   Request for GET 127.0.0.1:36701/webapi/find falling back to PLAIN HTTP webclient/webclient.go:137
DEBU   Terminating Auth service process pid:28386 test:TestIntegrationAuth/TestPing integration/authservice.go:119
DEBU   Looking up Teleport Enterprise distribution v10.0.0 test:TestIntegration/TestVersion integration/download.go:65
DEBU   Teleport binaries are found in /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin. No need to download anything test:TestIntegration/TestVersion integration/download.go:173
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/teleport version test:TestIntegration/TestVersion integration/integration.go:508
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/tctl version test:TestIntegration/TestVersion integration/integration.go:508
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/tsh version test:TestIntegration/TestVersion integration/integration.go:508
DEBU   License is given as a string, writing it to a file test:TestIntegration/TestVersion integration/integration.go:146
DEBU   Looking up Teleport Enterprise distribution v10.0.0 test:TestIntegrationProxy/TestPing integration/download.go:65
DEBU   Teleport binaries are found in /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin. No need to download anything test:TestIntegrationProxy/TestPing integration/download.go:173
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/teleport version test:TestIntegrationProxy/TestPing integration/integration.go:508
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/tctl version test:TestIntegrationProxy/TestPing integration/integration.go:508
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/tsh version test:TestIntegrationProxy/TestPing integration/integration.go:508
DEBU   License is given as a string, writing it to a file test:TestIntegrationProxy/TestPing integration/integration.go:146
DEBU   Running Auth service: /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/teleport start --debug --config /tmp/teleport-plugins-integration-4060495842/teleport-auth-1789928086.yaml test:TestIntegrationProxy/TestPing integration/authservice.go:90
DEBU   Auth service process has been started pid:28688 test:TestIntegrationProxy/TestPing integration/authservice.go:113
DEBU   Found addr of Auth service process: 127.0.0.1:33275 pid:28688 test:TestIntegrationProxy/TestPing integration/authservice.go:151
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/tctl --config /tmp/teleport-plugins-integration-4060495842/teleport-auth-1789928086.yaml --auth-server 127.0.0.1:33275 status test:TestIntegrationProxy/TestPing tctl/tctl.go:140
DEBU   Running Proxy service: /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/teleport start --debug --config /tmp/teleport-plugins-integration-4060495842/teleport-proxy-1348629473.yaml test:TestIntegrationProxy/TestPing integration/proxyservice.go:95
DEBU   Proxy service process has been started pid:28737 test:TestIntegrationProxy/TestPing integration/proxyservice.go:118
DEBU   Found all addrs of Proxy service process addr_ssh:127.0.0.1:0 addr_tun:localhost:41283 addr_web:localhost:42729 pid:28737 test:TestIntegrationProxy/TestPing integration/proxyservice.go:165
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/tctl --config /tmp/teleport-plugins-integration-4060495842/teleport-auth-1789928086.yaml --auth-server 127.0.0.1:33275 create test:TestIntegrationProxy/TestPing tctl/tctl.go:73
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/tctl --config /tmp/teleport-plugins-integration-4060495842/teleport-auth-1789928086.yaml --auth-server 127.0.0.1:33275 auth sign --user vladimir --format file --overwrite --out /tmp/teleport-plugins-integration-4060495842/credentials-vladimir-3447046333 test:TestIntegrationProxy/TestPing tctl/tctl.go:59
DEBU   Attempting GET localhost:42729/webapi/find webclient/webclient.go:119
DEBU   Attempting GET localhost:42729/webapi/find webclient/webclient.go:119
DEBU   Terminating Proxy service process pid:28737 test:TestIntegrationProxy/TestPing integration/proxyservice.go:124
DEBU   Terminating Auth service process pid:28688 test:TestIntegrationProxy/TestPing integration/authservice.go:119
DEBU   Looking up Teleport Enterprise distribution v10.0.0 test:TestIntegrationSSH/TestBench integration/download.go:65
DEBU   Teleport binaries are found in /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin. No need to download anything test:TestIntegrationSSH/TestBench integration/download.go:173
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/teleport version test:TestIntegrationSSH/TestBench integration/integration.go:508
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/tctl version test:TestIntegrationSSH/TestBench integration/integration.go:508
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/tsh version test:TestIntegrationSSH/TestBench integration/integration.go:508
DEBU   License is given as a string, writing it to a file test:TestIntegrationSSH/TestBench integration/integration.go:146
DEBU   Running Auth service: /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/teleport start --debug --config /tmp/teleport-plugins-integration-1003355266/teleport-auth-160722111.yaml test:TestIntegrationSSH/TestBench integration/authservice.go:90
DEBU   Auth service process has been started pid:28806 test:TestIntegrationSSH/TestBench integration/authservice.go:113
DEBU   Found addr of Auth service process: 127.0.0.1:45307 pid:28806 test:TestIntegrationSSH/TestBench integration/authservice.go:151
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/tctl --config /tmp/teleport-plugins-integration-1003355266/teleport-auth-160722111.yaml --auth-server 127.0.0.1:45307 status test:TestIntegrationSSH/TestBench tctl/tctl.go:140
DEBU   Running Proxy service: /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/teleport start --debug --config /tmp/teleport-plugins-integration-1003355266/teleport-proxy-3274455281.yaml test:TestIntegrationSSH/TestBench integration/proxyservice.go:95
DEBU   Proxy service process has been started pid:28834 test:TestIntegrationSSH/TestBench integration/proxyservice.go:118
DEBU   Found all addrs of Proxy service process addr_ssh:127.0.0.1:0 addr_tun:localhost:45301 addr_web:localhost:39847 pid:28834 test:TestIntegrationSSH/TestBench integration/proxyservice.go:165
DEBU   Running SSH service: /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/teleport start --debug --config /tmp/teleport-plugins-integration-1003355266/teleport-ssh-819810309.yaml test:TestIntegrationSSH/TestBench integration/sshservice.go:90
DEBU   SSH service process has been started pid:28848 test:TestIntegrationSSH/TestBench integration/sshservice.go:113
DEBU   Found addr of SSH service process: 127.0.0.1:33339 pid:28848 test:TestIntegrationSSH/TestBench integration/sshservice.go:151
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/tctl --config /tmp/teleport-plugins-integration-1003355266/teleport-auth-160722111.yaml --auth-server 127.0.0.1:45307 create test:TestIntegrationSSH/TestBench tctl/tctl.go:73
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/tctl --config /tmp/teleport-plugins-integration-1003355266/teleport-auth-160722111.yaml --auth-server 127.0.0.1:45307 auth sign --user root --format file --overwrite --out /tmp/teleport-plugins-integration-1003355266/credentials-root-528550020 test:TestIntegrationSSH/TestBench tctl/tctl.go:59
DEBU   Running /workspace/.teleport/teleport-ent-v10.0.0-linux-amd64-bin/tsh --insecure --identity /tmp/teleport-plugins-integration-1003355266/credentials-root-528550020 --proxy localhost:39847,0 bench root@localhost ls test:TestIntegrationSSH/TestBench tsh/tsh.go:79
DEBU   Terminating SSH service process pid:28848 test:TestIntegrationSSH/TestBench integration/sshservice.go:119
DEBU   Terminating Proxy service process pid:28834 test:TestIntegrationSSH/TestBench integration/proxyservice.go:124
DEBU   Terminating Auth service process pid:28806 test:TestIntegrationSSH/TestBench integration/authservice.go:119
--- FAIL: TestIntegrationSSH (4.05s)
    --- FAIL: TestIntegrationSSH/TestBench (4.04s)
        ssh_test.go:57: 
            	Error Trace:	ssh_test.go:57
            	Error:      	Should be zero, but was 2
            	Test:       	TestIntegrationSSH/TestBench
FAIL
FAIL	github.com/gravitational/teleport-plugins/lib/testing/integration	20.272s
```

### PR DESCRIPTION
**Pull request by marcoandredinis**
We were only checking for the following message to be present
`Service <xyz> is starting on <host:port>`

But that's not exactly when the port is open and accepting new clients.
We need to wait a little longer, so we are now waiting for a new line to
appear:
```
The new service has started successfully.
```

We also added a couple extra checks to ensure the service is ready to
receive clients.

Running the test multiple times with the `-race` flag works as expected:
```
marco@lenix ~/s/teleport-plugins (marco/fix_testbench)> go test ./lib/testing/integration -count 20 -race
ok      github.com/gravitational/teleport-plugins/lib/testing/integration       293.213s
```

Fixes #645

### CODE REVIEW

File: lib/tctl/resources.go [hunk 1]
```diff
@@ -68,6 +68,13 @@ func (res *streamResource) UnmarshalJSON(raw []byte) error {
 
 	var resource types.Resource
 	switch header.Kind {
+	case types.KindNode:
```
Comment (tcsc) [inline lib/tctl/resources.go:71]: Does this relate to the tests?

**Review by tcsc — APPROVED** [review]

**Review by Joerger — APPROVED** [review]

File: lib/tctl/resources.go (hunk 1 above)
Comment (marcoandredinis) [reply lib/tctl/resources.go:71]: Yes
We are querying all the nodes to ensure we can proceed with the test here
https://github.com/gravitational/teleport-plugins/blob/7866f13d8cbf60db86f5390db41563c90853db70/lib/testing/integration/setup.go#L122

File: lib/testing/integration/proxyservice.go [hunk 2]
```diff
@@ -158,12 +158,14 @@ func (proxy *ProxyService) Run(ctx context.Context) error {
 					tunAddr := proxy.reverseTunnelAddr
 					proxy.mu.Unlock()
 					if !webAddr.IsEmpty() && !sshAddr.IsEmpty() && !tunAddr.IsEmpty() {
-						log.WithFields(logger.Fields{
-							"addr_web": webAddr,
-							"addr_ssh": sshAddr,
-							"addr_tun": tunAddr,
-						}).Debugf("Found all addrs of Proxy service process")
-						proxy.setReady(true)
+						if strings.Contains(line, "List of known proxies updated:") {
```
[the remark this answers is not in the document]
Comment (marcoandredinis) [reply lib/testing/integration/proxyservice.go:161]: Re-ordered the if's
It's more readable now, still not perfect though :sweat_smile: 
Let me know what do you think

File: lib/testing/integration/sshservice.go [hunk 3]
```diff
@@ -148,8 +148,10 @@ func (ssh *SSHService) Run(ctx context.Context) error {
 				ssh.parseLine(ctx, line)
 				if !ssh.IsReady() {
 					if addr := ssh.Addr(); !addr.IsEmpty() {
-						log.Debugf("Found addr of SSH service process: %v", addr)
-						ssh.setReady(true)
+						if strings.Contains(line, "The new service has started successfully.") {
```
[the remark this answers is not in the document]
Comment (marcoandredinis) [reply lib/testing/integration/sshservice.go:151]: We use the binary's output for two things:
- tcp port
- know when the service is ready

We already know the TCP port, so we could remove that part from log parsing.
We are using `getFreeTCPPort`, which can fail (bind, release and re-use).
This method was removed in the `teleport` main repo but I'm not sure we could do the same here without changing too many things.

The other issue - when is the service ready?
We could try to open a TCP connection and only proceed when that is successful.


Anyway, I would rather open a new PR for those changes.
What do you think?

File: lib/testing/integration/authservice.go [hunk 4]
```diff
@@ -143,23 +143,25 @@ func (auth *AuthService) Run(ctx context.Context) error {
...
 			}
 			if err := trace.Wrap(err); err != nil {
 				log.WithError(err).Error("failed to read process stdout")
 				return
 			}
+
+			auth.saveStdout(line)
+
+			if auth.IsReady() {
+				continue
```
Comment (zmb3) [inline lib/testing/integration/authservice.go:157]: Is this correct? Won't this put us in a busy loop if auth is ready?

Comment (marcoandredinis) [reply lib/testing/integration/authservice.go:157]: It shouldn't, unless I'm missing something.

The first line of the loop calls `line, err := stdout.ReadString('\n')` which should block until a new line is returned (it could be an empty one, but that shouldn't matter for this use case)

**Comment by marcoandredinis** [comment]
@zmb3 Can you please take another look when you get a chance?

**Review by zmb3 — APPROVED** [review]
I really don't like the fact that we're parsing log output to determine what actions to take. Seems so fragile.

Approving though, as I recognize this isn't new to this PR.

**Comment by marcoandredinis** [comment]
> I really don't like the fact that we're parsing log output to determine what actions to take. Seems so fragile.
> 
> Approving though, as I recognize this isn't new to this PR.

Agreed :+1: 
I think I'll add a `require.Eventually` to ensure the test continues only when we can use the newly created service
