### PR TITLE
Don't use the same CN for all mTLS certs

### LINKED ISSUE #747: [event forwarder] configure command outputs non-working setup
When using the `teleport-event-handler configure` command, it generates a self-signed ca and signs a server cert and a client cert. All three certs have _identical_ subject names. This seems to work on some TLS implementations and not others.

The error that happens is the plugin will start up, but as soon as it tries to connect to the fluentd endpoint, it will throw errors related to the cert: `ERRO   Error sending event to Teleport: Post "https://localhost:8888/test.log": remote error: tls: unknown certificate authority event-handler/app.go:118`

<details>
<summary>Click to expand full log output</summary>

```
./teleport-event-handler start --config teleport-event-handler.toml
INFO   Using batch size batch:20 event-handler/cli.go:236
INFO   Using namespace namespace:default event-handler/cli.go:237
INFO   Using type filter types:[] event-handler/cli.go:238
INFO   Skipping session events of type types:map[print:{}] event-handler/cli.go:239
INFO   Using start time value:<nil> event-handler/cli.go:240
INFO   Using timeout timeout:10s event-handler/cli.go:241
INFO   Using Fluentd url url:https://localhost:8888/test.log event-handler/cli.go:242
INFO   Using Fluentd session url url:https://localhost:8888/session event-handler/cli.go:243
INFO   Using Fluentd ca ca:/opt/event-handler/ca.crt event-handler/cli.go:244
INFO   Using Fluentd cert cert:/opt/event-handler/client.crt event-handler/cli.go:245
INFO   Using Fluentd key key:/opt/event-handler/client.key event-handler/cli.go:246
INFO   Using Teleport identity file file:/opt/event-handler/identity event-handler/cli.go:249
INFO   Created storage directory dir:storage/teleport.example.com_443 event-handler/state.go:112
WARN   open : no such file or directory event-handler/teleport_events_watcher.go:85
INFO   At least one non-expired credential has been found, continuing startup event-handler/teleport_events_watcher.go:91
INFO   Using initial cursor value cursor: event-handler/app.go:191
INFO   Using initial ID value id: event-handler/app.go:192
INFO   Using start time from state value:2023-01-25 21:56:06 +0000 UTC event-handler/app.go:193
ERRO   Error sending event to Teleport: Post "https://localhost:8888/test.log": remote error: tls: unknown certificate authority event-handler/app.go:118
ERRO   Error sending event to Teleport: Post "https://localhost:8888/test.log": remote error: tls: unknown certificate authority event-handler/app.go:118
ERRO   Error sending event to Teleport: Post "https://localhost:8888/test.log": remote error: tls: unknown certificate authority event-handler/app.go:118
ERRO   Error sending event to Teleport: Post "https://localhost:8888/test.log": remote error: tls: unknown certificate authority event-handler/app.go:118
ERRO   Error sending event to Teleport: Post "https://localhost:8888/test.log": remote error: tls: unknown certificate authority event-handler/app.go:118
ERRO   Error sending event to Teleport: Post "https://localhost:8888/test.log": remote error: tls: unknown certificate authority event-handler/app.go:118
^CINFO   Attempting graceful shutdown... lib/signals.go:46
ERRO   Watcher event loop failed error:[
ERROR REPORT:
Original Error: *url.Error Post &#34;https://localhost:8888/test.log&#34;: remote error: tls: unknown certificate authority
Stack Trace:
	/go/src/github.com/gravitational/teleport-plugins/event-handler/fluentd_client.go:108 main.(*FluentdClient).Send
	/go/src/github.com/gravitational/teleport-plugins/event-handler/app.go:113 main.(*App).SendEvent
	/go/src/github.com/gravitational/teleport-plugins/event-handler/events_job.go:149 main.(*EventsJob).sendEvent
	/go/src/github.com/gravitational/teleport-plugins/event-handler/events_job.go:118 main.(*EventsJob).handleEvent
	/go/src/github.com/gravitational/teleport-plugins/event-handler/events_job.go:104 main.(*EventsJob).runPolling
	/go/src/github.com/gravitational/teleport-plugins/event-handler/events_job.go:65 main.(*EventsJob).run
	/go/src/github.com/gravitational/teleport-plugins/lib/process.go:230 github.com/gravitational/teleport-plugins/lib.NewServiceJob.func1
	/go/src/github.com/gravitational/teleport-plugins/lib/process.go:251 github.com/gravitational/teleport-plugins/lib.(*serviceJob).DoJob
	/go/src/github.com/gravitational/teleport-plugins/lib/process.go:97 github.com/gravitational/teleport-plugins/lib.NewProcess.func2.1
	/usr/local/go/src/runtime/asm_amd64.s:1594 runtime.goexit
User Message: Post &#34;https://localhost:8888/test.log&#34;: remote error: tls: unknown certificate authority] event-handler/events_job.go:81
ERRO   Terminating with fatal error [1]... error:[
ERROR REPORT:
Original Error: *url.Error Post &#34;https://localhost:8888/test.log&#34;: remote error: tls: unknown certificate authority
Stack Trace:
	/go/src/github.com/gravitational/teleport-plugins/event-handler/fluentd_client.go:108 main.(*FluentdClient).Send
	/go/src/github.com/gravitational/teleport-plugins/event-handler/app.go:113 main.(*App).SendEvent
	/go/src/github.com/gravitational/teleport-plugins/event-handler/events_job.go:149 main.(*EventsJob).sendEvent
	/go/src/github.com/gravitational/teleport-plugins/event-handler/events_job.go:118 main.(*EventsJob).handleEvent
	/go/src/github.com/gravitational/teleport-plugins/event-handler/events_job.go:104 main.(*EventsJob).runPolling
	/go/src/github.com/gravitational/teleport-plugins/event-handler/events_job.go:65 main.(*EventsJob).run
	/go/src/github.com/gravitational/teleport-plugins/lib/process.go:230 github.com/gravitational/teleport-plugins/lib.NewServiceJob.func1
	/go/src/github.com/gravitational/teleport-plugins/lib/process.go:251 github.com/gravitational/teleport-plugins/lib.(*serviceJob).DoJob
	/go/src/github.com/gravitational/teleport-plugins/lib/process.go:97 github.com/gravitational/teleport-plugins/lib.NewProcess.func2.1
	/usr/local/go/src/runtime/asm_amd64.s:1594 runtime.goexit
User Message: Post &#34;https://localhost:8888/test.log&#34;: remote error: tls: unknown certificate authority] lib/bail.go:28
```

</details>

<details>
<summary>teleport-event-handler.toml</summary>

```toml
storage = "./storage"
timeout = "10s"
batch = 20
namespace = "default"

[forward.fluentd]
ca = "/opt/event-handler/ca.crt"
cert = "/opt/event-handler/client.crt"
key = "/opt/event-handler/client.key"
url = "https://localhost:8888/test.log"
session-url = "https://localhost:8888/session"

[teleport]
addr = "teleport.example.com:443"
identity = "identity"
```

</details>

```
for i in ca.crt client.crt server.crt; do openssl x509 -noout -subject -serial -in ${i}; done
subject=C = US, CN = localhost
serial=ACFC656D7263BCFABA7C19AA86D04F78
subject=C = US, CN = localhost
serial=881D414631868529C964946D5A315B73
subject=C = US, CN = localhost
serial=26DFB5FA3C9A598F7AD7DB59EC26DF5B
```

If the subject was different for each cert, this would avoid the problem altogether.

### Workarounds

Generate your own CA, client, and server certificates instead of using the generated certs.

### Steps to Reproduce

Follow the guide found here: https://goteleport.com/docs/management/export-audit-events/fluentd/?scope=enterprise

The error happens on a fresh ubuntu 22.04 environment, which has `OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)` installed on it.

The same steps on my mac that has `LibreSSL 3.3.6`, plus all the apple trust store extensions for its openssl and tls libraries does not reproduce the problem.

### PR DESCRIPTION
**Pull request by skodde**
Use a unique Common Name for each certificate type when generating
the event handler mTLS certificates, instead of reusing the same
Common Name for all.

Fixes #747

### CODE REVIEW

**Comment by programmerq** [comment]
To recreate the problem described by #747, I wrote this script:

```bash
#!/bin/bash

T=$(mktemp -d)

./build/teleport-event-handler configure ${T} fluentd.example.com:443

alias libressl=/usr/local/openssl
alias openssl1=/usr/local/Cellar/openssl@1.1/1.1.1v/bin/openssl
alias openssl3=/usr/local/Cellar/openssl@3/3.1.2/bin/openssl


for openssl in /usr/local/bin/openssl /usr/local/Cellar/openssl@1.1/1.1.1v/bin/openssl /usr/local/Cellar/openssl@3/3.1.2/bin/openssl; do
	$openssl verify -purpose sslserver -CAfile ${T}/ca.crt ${T}/server.crt
	$openssl verify -purpose sslclient -CAfile ${T}/ca.crt ${T}/client.crt
done
```

My mac has libressl, openssl1.x, and openssl3.x installed, so I repeat the test for each library.

When running this script with a binary built from master, the generated certs fail to verify. When I run with a binary built by this code change, it successfully verifies. This pass/fail corresponds with the pass/fail pattern seen when running the full setup per the instructions here: https://goteleport.com/docs/management/export-audit-events/fluentd/

**Review by programmerq — APPROVED** [review]
LGTM!

**Review by r0mant — COMMENTED** [review]
@skodde Can you add test coverage in https://github.com/gravitational/teleport-plugins/blob/5af78777ea26e914cd60349e8cb8aceb3f169544/event-handler/mtls_certs_test.go?

**Review by tcsc — APPROVED** [review]
Looks good to me once @r0mant's comment addressed

**Review by Joerger — APPROVED** [review]

**Comment by programmerq** [comment]
> @skodde Can you add test coverage in https://github.com/gravitational/teleport-plugins/blob/5af78777ea26e914cd60349e8cb8aceb3f169544/event-handler/mtls_certs_test.go?

Since @skodde is out today, I added tests in https://github.com/gravitational/teleport-plugins/pull/901/commits/fc474326975c546e99b30f18a8a59004fb1dcf41

File: event-handler/mtls_certs_test.go [hunk 1]
```diff
@@ -40,6 +40,14 @@ func TestGenerateClientCertFile(t *testing.T) {
 	require.NotNil(t, certs.clientCert.Issuer)
 	require.NotNil(t, certs.serverCert.Issuer)
 
+	// make sure certs are different
+	require.NotEqual(t, certs.caCert.Subject.CommonName, certs.clientCert.Subject.CommonName, "CA and client certs should be different")
+	require.NotEqual(t, certs.caCert.Subject.CommonName, certs.serverCert.Subject.CommonName, "CA and server certs should be different")
+
+	// Server cert should have SAN
+	require.NotNil(t, certs.serverCert.DNSNames)
```
Comment (zmb3) [inline event-handler/mtls_certs_test.go:48]:
```suggestion
	require.NotEmpty(t, certs.serverCert.DNSNames)
```

File: event-handler/mtls_certs_test.go [hunk 2]
```diff
@@ -40,6 +40,14 @@ func TestGenerateClientCertFile(t *testing.T) {
...
+	require.Equal(t, certs.serverCert.DNSNames[0], "localhost")
```
Comment (zmb3) [inline event-handler/mtls_certs_test.go:49]:
```suggestion
	require.Equal(t, "localhost", certs.serverCert.DNSNames[0])
```

expected value first, then actual value (otherwise you'll get a very confusing error message on failure)

**Review by zmb3 — APPROVED** [review]
